### PR TITLE
Added Animation with Prop and Usable Item

### PR DESCRIPTION
**Pull request by LeSiiN**
- added Tablet Animation with Prop ( prop can be changed in config )
- added check if player is dead/inlaststand/handcuffed or in pause menu
- added usable item ( can be deactivated/activated in config) , item can be changed in config aswell
- added config for deactivate/activate command

### CODE REVIEW

**Comment by ImXirvin** [comment]
Where do they get the item?

**Comment by complexza** [comment]
I am supposed to make a target zone for public people to view houses, then with that zone real estate agents can collect the tablet, still deciding if I want it to be free or open a shop.

**Comment by LeSiiN** [comment]
> Where do they get the item?

they add the item to any shop of they liking, thats not our part to make that a thing

**Comment by MonkeyWhisper** [comment]
Hi,

Please resubmit PR once we finish the new UI. Will take 2 weeks or so.

**Comment by complexza** [comment]
will do

**Pull request closed without merging**
